

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: [ubuntu-latest, windows-lastest]

    steps:
      - uses: actions/checkout@v3

      - name: Ejecutar tests
        run: 
         ServicioCafeteriaTest.java

